root = "."
testdata_dir = "testdata"
tmp_dir = "/tmp"

[build]
  cmd = "make build"
  bin = "/tmp/main standalone-server"
  full_bin = "dlv exec --listen=:2345 --continue --accept-multiclient --headless --api-version=2  /tmp/main standalone-server"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["docker", "test"]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
