version: '3.8'

services:
  go:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    ports:
      - 8080:8080
      - 2345:2345
    volumes:
      - .:/app
    tty: true

  mysql:
    image: mysql:8.0.30
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=go_load
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root

  redis:
    image: redis:7.2.5
    restart: always
    ports:
      - 6379:6379

  zookeeper:
    image: 'bitnami/zookeeper:3.8-debian-10'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: always

  kafka:
    image: 'bitnami/kafka:3.1-debian-10'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    restart: always

  # https://min.io/docs/minio/container/index.html#procedurehttps://min.io/docs/minio/container/index.html#procedure
  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=ROOTNAME
      - MINIO_ROOT_PASSWORD=CHANGEME123
    restart: always
