database:
  type: "mysql"
  host: "mysql"
  port: 3306
  username: "user"
  password: "password"
  database: "go_load" 

cache:
  type: "redis"
  address: "redis:6379"
  username: ""
  password: ""

log:
  level: info

auth:
  hash:
    cost: 10
  token:
    expires_in: 1h
    regenerate_token_before_expiry: 1h

grpc:
  address: '127.0.0.1:8081'
  get_download_task_file:
    response_buffer_size: 1kB

http:
  address: '0.0.0.0:8080'

mq:
  addresses:
    - kafka:9092
  client_id: "goload"

download:
  mode: "s3"
  bucket: "downloaded-files"
  address: "minio:9000"
  username: "ROOTNAME"
  password: "CHANGEME123"
  download_directory: "downloaded_files"
